version: "3.4"

services:
  redis:
    container_name: env_redis
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
